# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_graphql_response_data import OneOfGraphqlResponseData  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfGraphqlResponseData(unittest.TestCase):
    """OneOfGraphqlResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfGraphqlResponseData(self):
        """Test OneOfGraphqlResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_graphql_response_data.OneOfGraphqlResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
