# coding: utf-8

"""
    Simple Inventory API

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_problems_topic_get(self):
        """Test case for api_problems_topic_get

        """
        pass

    def test_problems_problem_interpret_solution_post(self):
        """Test case for problems_problem_interpret_solution_post

        """
        pass

    def test_problems_problem_submit_post(self):
        """Test case for problems_problem_submit_post

        """
        pass

    def test_submissions_detail_id_check_get(self):
        """Test case for submissions_detail_id_check_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
