# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import, annotations

import unittest

import leetcode
from leetcode.models.any_of_graphql_query_variables import (  # noqa: E501
    AnyOfGraphqlQueryVariables,
)
from leetcode.rest import ApiException


class TestAnyOfGraphqlQueryVariables(unittest.TestCase):
    """AnyOfGraphqlQueryVariables unit test stubs"""

    def setUp(self) -> None:
        pass

    def tearDown(self) -> None:
        pass

    def testAnyOfGraphqlQueryVariables(self) -> None:
        """Test AnyOfGraphqlQueryVariables"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leetcode.models.any_of_graphql_query_variables.AnyOfGraphqlQueryVariables()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
