# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import leetcode
from leetcode.models.graphql_question_code_snippet import GraphqlQuestionCodeSnippet  # noqa: E501
from leetcode.rest import ApiException


class TestGraphqlQuestionCodeSnippet(unittest.TestCase):
    """GraphqlQuestionCodeSnippet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGraphqlQuestionCodeSnippet(self):
        """Test GraphqlQuestionCodeSnippet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leetcode.models.graphql_question_code_snippet.GraphqlQuestionCodeSnippet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
