# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import, annotations

import unittest

import leetcode
from leetcode.models.graphql_data import GraphqlData  # noqa: E501
from leetcode.rest import ApiException


class TestGraphqlData(unittest.TestCase):
    """GraphqlData unit test stubs"""

    def setUp(self) -> None:
        pass

    def tearDown(self) -> None:
        pass

    def testGraphqlData(self) -> None:
        """Test GraphqlData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leetcode.models.graphql_data.GraphqlData()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
