# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import, annotations

import unittest

import leetcode
from leetcode.models.graphql_query_problemset_question_list_variables import (  # noqa: E501
    GraphqlQueryProblemsetQuestionListVariables,
)
from leetcode.rest import ApiException


class TestGraphqlQueryProblemsetQuestionListVariables(unittest.TestCase):
    """GraphqlQueryProblemsetQuestionListVariables unit test stubs"""

    def setUp(self) -> None:
        pass

    def tearDown(self) -> None:
        pass

    def testGraphqlQueryProblemsetQuestionListVariables(self) -> None:
        """Test GraphqlQueryProblemsetQuestionListVariables"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leetcode.models.graphql_query_problemset_question_list_variables.GraphqlQueryProblemsetQuestionListVariables()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
