# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import leetcode
from leetcode.models.graphql_query_variables import GraphqlQueryVariables  # noqa: E501
from leetcode.rest import ApiException


class TestGraphqlQueryVariables(unittest.TestCase):
    """GraphqlQueryVariables unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGraphqlQueryVariables(self):
        """Test GraphqlQueryVariables"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leetcode.models.graphql_query_variables.GraphqlQueryVariables()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
