# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import leetcode
from leetcode.models.one_ofinline_response200 import (  # noqa: E501
    OneOfinlineResponse200,
)
from leetcode.rest import ApiException


class TestOneOfinlineResponse200(unittest.TestCase):
    """OneOfinlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfinlineResponse200(self):
        """Test OneOfinlineResponse200"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leetcode.models.one_ofinline_response200.OneOfinlineResponse200()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
