# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import, annotations

import unittest

import leetcode
from leetcode.models.graphql_question_code_snippet import (  # noqa: E501
    GraphqlQuestionCodeSnippet,
)
from leetcode.rest import ApiException


class TestGraphqlQuestionCodeSnippet(unittest.TestCase):
    """GraphqlQuestionCodeSnippet unit test stubs"""

    def setUp(self) -> None:
        pass

    def tearDown(self) -> None:
        pass

    def testGraphqlQuestionCodeSnippet(self) -> None:
        """Test GraphqlQuestionCodeSnippet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leetcode.models.graphql_question_code_snippet.GraphqlQuestionCodeSnippet()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
