# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import leetcode
from leetcode.models.one_ofid import OneOfid  # noqa: E501
from leetcode.rest import ApiException


class TestOneOfid(unittest.TestCase):
    """OneOfid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfid(self):
        """Test OneOfid"""
        # FIXME: construct object with mandatory attributes with example values
        # model = leetcode.models.one_ofid.OneOfid()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
