# coding: utf-8

# flake8: noqa
"""
    Simple Inventory API

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.difficulty import Difficulty
from swagger_client.models.problems import Problems
from swagger_client.models.stat import Stat
from swagger_client.models.stat_status_pair import StatStatusPair
