# coding: utf-8

# flake8: noqa
"""
    Simple Inventory API

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.base_submission_result import BaseSubmissionResult
from swagger_client.models.difficulty import Difficulty
from swagger_client.models.graphql_query import GraphqlQuery
from swagger_client.models.graphql_query_variables import GraphqlQueryVariables
from swagger_client.models.graphql_question import GraphqlQuestion
from swagger_client.models.graphql_question_detail import GraphqlQuestionDetail
from swagger_client.models.graphql_response import GraphqlResponse
from swagger_client.models.id import Id
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.interpretation import Interpretation
from swagger_client.models.one_of_graphql_response_data import OneOfGraphqlResponseData
from swagger_client.models.one_ofid import OneOfid
from swagger_client.models.one_ofinline_response200 import OneOfinlineResponse200
from swagger_client.models.problems import Problems
from swagger_client.models.stat import Stat
from swagger_client.models.stat_status_pair import StatStatusPair
from swagger_client.models.submission import Submission
from swagger_client.models.submission_id import SubmissionId
from swagger_client.models.submission_result import SubmissionResult
from swagger_client.models.test_submission import TestSubmission
from swagger_client.models.test_submission_result import TestSubmissionResult
