# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from __future__ import annotations

import pprint
import re  # noqa: F401

import six


class GraphqlQuestionSolution(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"id": "str", "can_see_detail": "bool", "typename": "str"}

    attribute_map = {
        "id": "id",
        "can_see_detail": "canSeeDetail",
        "typename": "__typename",
    }

    def __init__(
        self, id=None, can_see_detail=None, typename=None
    ) -> None:  # noqa: E501
        """GraphqlQuestionSolution - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._can_see_detail = None
        self._typename = None
        self.discriminator = None
        self.id = id
        self.can_see_detail = can_see_detail
        self.typename = typename

    @property
    def id(self):
        """Gets the id of this GraphqlQuestionSolution.  # noqa: E501


        :return: The id of this GraphqlQuestionSolution.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GraphqlQuestionSolution.


        :param id: The id of this GraphqlQuestionSolution.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def can_see_detail(self):
        """Gets the can_see_detail of this GraphqlQuestionSolution.  # noqa: E501


        :return: The can_see_detail of this GraphqlQuestionSolution.  # noqa: E501
        :rtype: bool
        """
        return self._can_see_detail

    @can_see_detail.setter
    def can_see_detail(self, can_see_detail):
        """Sets the can_see_detail of this GraphqlQuestionSolution.


        :param can_see_detail: The can_see_detail of this GraphqlQuestionSolution.  # noqa: E501
        :type: bool
        """
        if can_see_detail is None:
            raise ValueError(
                "Invalid value for `can_see_detail`, must not be `None`"
            )  # noqa: E501

        self._can_see_detail = can_see_detail

    @property
    def typename(self):
        """Gets the typename of this GraphqlQuestionSolution.  # noqa: E501


        :return: The typename of this GraphqlQuestionSolution.  # noqa: E501
        :rtype: str
        """
        return self._typename

    @typename.setter
    def typename(self, typename):
        """Sets the typename of this GraphqlQuestionSolution.


        :param typename: The typename of this GraphqlQuestionSolution.  # noqa: E501
        :type: str
        """
        if typename is None:
            raise ValueError(
                "Invalid value for `typename`, must not be `None`"
            )  # noqa: E501

        self._typename = typename

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(GraphqlQuestionSolution, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: GraphqlQuestionSolution) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GraphqlQuestionSolution):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
