# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GraphqlData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"question": "GraphqlQuestionDetail", "user": "GraphqlUser"}

    attribute_map = {"question": "question", "user": "user"}

    def __init__(self, question=None, user=None):  # noqa: E501
        """GraphqlData - a model defined in Swagger"""  # noqa: E501
        self._question = None
        self._user = None
        self.discriminator = None
        if question is not None:
            self.question = question
        if user is not None:
            self.user = user

    @property
    def question(self):
        """Gets the question of this GraphqlData.  # noqa: E501


        :return: The question of this GraphqlData.  # noqa: E501
        :rtype: GraphqlQuestionDetail
        """
        return self._question

    @question.setter
    def question(self, question):
        """Sets the question of this GraphqlData.


        :param question: The question of this GraphqlData.  # noqa: E501
        :type: GraphqlQuestionDetail
        """

        self._question = question

    @property
    def user(self):
        """Gets the user of this GraphqlData.  # noqa: E501


        :return: The user of this GraphqlData.  # noqa: E501
        :rtype: GraphqlUser
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this GraphqlData.


        :param user: The user of this GraphqlData.  # noqa: E501
        :type: GraphqlUser
        """

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(GraphqlData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GraphqlData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
