# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from __future__ import annotations

import pprint
import re  # noqa: F401

import six


class GraphqlProblemsetQuestionList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"total_num": "int", "questions": "list[GraphqlQuestionDetail]"}

    attribute_map = {"total_num": "totalNum", "questions": "questions"}

    def __init__(self, total_num=None, questions=None) -> None:  # noqa: E501
        """GraphqlProblemsetQuestionList - a model defined in Swagger"""  # noqa: E501
        self._total_num = None
        self._questions = None
        self.discriminator = None
        if total_num is not None:
            self.total_num = total_num
        if questions is not None:
            self.questions = questions

    @property
    def total_num(self):
        """Gets the total_num of this GraphqlProblemsetQuestionList.  # noqa: E501


        :return: The total_num of this GraphqlProblemsetQuestionList.  # noqa: E501
        :rtype: int
        """
        return self._total_num

    @total_num.setter
    def total_num(self, total_num):
        """Sets the total_num of this GraphqlProblemsetQuestionList.


        :param total_num: The total_num of this GraphqlProblemsetQuestionList.  # noqa: E501
        :type: int
        """

        self._total_num = total_num

    @property
    def questions(self):
        """Gets the questions of this GraphqlProblemsetQuestionList.  # noqa: E501


        :return: The questions of this GraphqlProblemsetQuestionList.  # noqa: E501
        :rtype: list[GraphqlQuestionDetail]
        """
        return self._questions

    @questions.setter
    def questions(self, questions):
        """Sets the questions of this GraphqlProblemsetQuestionList.


        :param questions: The questions of this GraphqlProblemsetQuestionList.  # noqa: E501
        :type: list[GraphqlQuestionDetail]
        """

        self._questions = questions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(GraphqlProblemsetQuestionList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: GraphqlProblemsetQuestionList) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GraphqlProblemsetQuestionList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
