# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from __future__ import annotations

import pprint
import re  # noqa: F401

import six


class GraphqlQuestionTopicTag(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "name": "str",
        "slug": "str",
        "translated_name": "str",
        "typename": "str",
    }

    attribute_map = {
        "name": "name",
        "slug": "slug",
        "translated_name": "translatedName",
        "typename": "__typename",
    }

    def __init__(
        self, name=None, slug=None, translated_name=None, typename=None
    ) -> None:  # noqa: E501
        """GraphqlQuestionTopicTag - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._slug = None
        self._translated_name = None
        self._typename = None
        self.discriminator = None
        self.name = name
        self.slug = slug
        if translated_name is not None:
            self.translated_name = translated_name
        if typename is not None:
            self.typename = typename

    @property
    def name(self):
        """Gets the name of this GraphqlQuestionTopicTag.  # noqa: E501


        :return: The name of this GraphqlQuestionTopicTag.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GraphqlQuestionTopicTag.


        :param name: The name of this GraphqlQuestionTopicTag.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def slug(self):
        """Gets the slug of this GraphqlQuestionTopicTag.  # noqa: E501


        :return: The slug of this GraphqlQuestionTopicTag.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this GraphqlQuestionTopicTag.


        :param slug: The slug of this GraphqlQuestionTopicTag.  # noqa: E501
        :type: str
        """
        if slug is None:
            raise ValueError(
                "Invalid value for `slug`, must not be `None`"
            )  # noqa: E501

        self._slug = slug

    @property
    def translated_name(self):
        """Gets the translated_name of this GraphqlQuestionTopicTag.  # noqa: E501


        :return: The translated_name of this GraphqlQuestionTopicTag.  # noqa: E501
        :rtype: str
        """
        return self._translated_name

    @translated_name.setter
    def translated_name(self, translated_name):
        """Sets the translated_name of this GraphqlQuestionTopicTag.


        :param translated_name: The translated_name of this GraphqlQuestionTopicTag.  # noqa: E501
        :type: str
        """

        self._translated_name = translated_name

    @property
    def typename(self):
        """Gets the typename of this GraphqlQuestionTopicTag.  # noqa: E501


        :return: The typename of this GraphqlQuestionTopicTag.  # noqa: E501
        :rtype: str
        """
        return self._typename

    @typename.setter
    def typename(self, typename):
        """Sets the typename of this GraphqlQuestionTopicTag.


        :param typename: The typename of this GraphqlQuestionTopicTag.  # noqa: E501
        :type: str
        """

        self._typename = typename

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(GraphqlQuestionTopicTag, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: GraphqlQuestionTopicTag) -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, GraphqlQuestionTopicTag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
