# coding: utf-8

"""
    Leetcode API

    Leetcode API implementation.  # noqa: E501

    OpenAPI spec version: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GraphqlUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'is_current_user_premium': 'bool'
    }

    attribute_map = {
        'username': 'username',
        'is_current_user_premium': 'isCurrentUserPremium'
    }

    def __init__(self, username=None, is_current_user_premium=None):  # noqa: E501
        """GraphqlUser - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._is_current_user_premium = None
        self.discriminator = None
        if username is not None:
            self.username = username
        if is_current_user_premium is not None:
            self.is_current_user_premium = is_current_user_premium

    @property
    def username(self):
        """Gets the username of this GraphqlUser.  # noqa: E501


        :return: The username of this GraphqlUser.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this GraphqlUser.


        :param username: The username of this GraphqlUser.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def is_current_user_premium(self):
        """Gets the is_current_user_premium of this GraphqlUser.  # noqa: E501


        :return: The is_current_user_premium of this GraphqlUser.  # noqa: E501
        :rtype: bool
        """
        return self._is_current_user_premium

    @is_current_user_premium.setter
    def is_current_user_premium(self, is_current_user_premium):
        """Sets the is_current_user_premium of this GraphqlUser.


        :param is_current_user_premium: The is_current_user_premium of this GraphqlUser.  # noqa: E501
        :type: bool
        """

        self._is_current_user_premium = is_current_user_premium

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GraphqlUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GraphqlUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
