---
name: Tests
on: push
jobs:
  pytest:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install test requirements
        run: pip install -r test-requirements.txt
      - name: Install pytest
        run: pip install pytest
      - name: pip freeze (for debug purposes)
        run: pip freeze
      - name: Run tests
        run: pytest -vvvv -s
        env:
          LEETCODE_SESSION_ID: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN}}
